- name: "Extract availability, uptime and resources consumption of the app"
  ansible.builtin.command:
    cmd: systemctl status fastwebserver
  register: status
  changed_when: false

- name: "Printing fastwebserver service status"
  vars:
    msg: "{{ status.stdout_lines[0:9] }}"
  ansible.builtin.debug:
    msg: "{{ msg[4:10] }}"

- name: "Availability check and confirmation if the fastwebserver is down"
  ansible.builtin.debug:
    msg: "FastWebServer failed to start"
  when: ("running" not in status.stdout_lines[4]) 

- name: "Printing the fact that fastwebserver is up"
  ansible.builtin.debug:
    msg: "FastWebServer is up!" 

- name: "Find out the server OS status and resources consumption"
  ansible.builtin.shell: |
      set -o pipefail && \
      free -mh && \
      echo "--------------"
      uptime && \
      echo "--------------"
      top -b -n 1 | head -n +6 && \
      echo "--------------"
  register: output_perf
  changed_when: false

- name: "Printing the status of OS and resources"
  ansible.builtin.debug:
    var: output_perf.stdout_lines
    