
- name: "Move the systemd template to remote location and prepare to be started"
  ansible.builtin.template:
    src: ./templates/fast_web_server.j2
    dest: /etc/systemd/system/fastwebserver.service
    owner: root
    group: root
    mode: '0644'

- name: "Copy the fast webserver into remote location"
  ansible.builtin.copy:
    src: "{{ websrv.fast_webserver_local_location }}"
    dest: "{{ websrv.fast_webserver_remote_location }}"
    owner: fastwebserver
    group: fastwebserver
    mode: '0750'
  register: copy_result


- name: "Enable the fastwebserver systemd service"
  ansible.builtin.systemd_service:
    name: fastwebserver.service
    enabled: true 
    masked: false
    state: started
    daemon_reload: true
