- name: "Planned restart of the fastwebserver"
  hosts: web_servers
  tags: fast_webservers_restart
  force_handlers: true

  tasks:
    - name: "Check status of the server"
      ansible.builtin.command:
        cmd: systemctl status fastwebserver
      register: output
      changed_when: false
      ignore_errors: true
    
    - name: "Print the status of the server"
      ansible.builtin.debug:
        var: output.stdout_lines
      notify:
        - Restart_web_server

  handlers:
    - name: "Restart_web_server"
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: fastwebserver
      when: ("running" not in output.stdout_lines[4])


