- name: "Planned restart of the fastwebserver"
  hosts: web_servers
  tags: fast_webservers_restart

  vars:
    force_restart: "nok"

  tasks:
    - name: "Going with restarting the wev server"
      block:
        - name: "Check status of the server"
          ansible.builtin.shell:
            systemctl is-active fastwebserver
          register: output
          ignore_errors: true

        - name: "Restart web server"
          ansible.builtin.service:
            state: restarted
            name: fastwebserver
          when: (force_restart == 'ok') or ("active" not in output.stdout_lines)

        - name: "Print the server status"
          ansible.builtin.debug:
            var: output.stdout_lines
          
        - name: "Waiting for the fastwebserver to come back"
          check_mode: 
          ansible.builtin.wait_for:
            host: 0.0.0.0
            port: 8080
            delay: 3
            timeout: 60
            state: started
          when: (force_restart == 'ok') or ("active" not in output.stdout_lines)

    - name: "Check after restart"
      when: (force_restart == 'ok') or ("active" not in output.stdout_lines)
      block:    
        - name: "Check the status of the server after restart"
          ansible.builtin.shell:
            systemctl status fastwebserver
          register: final_after_restart
          ignore_errors: true

        - name: "Print the status after restart"
          ansible.builtin.debug:
            var: final_after_restart.stdout_lines[4:10]


