---
- name: "Prepare the hosts rhel based OS with proper tools for running as a server"
  hosts: all
  tags: os_internal_tools

  tasks:
    - name: "Load and execute tasks for installing internal tools for OS"
      ansible.builtin.include_tasks:
        file: ./tasks/install_os_tools.yml


- name: "Prepare java ecosystem"
  hosts: all
  tags: java_ecosystem

  tasks:
    - name: "Load and execute the java/graalvm tasks"
      ansible.builtin.include_tasks:
        file: ./tasks/prepare_java_ecosystem.yml


- name: "Config and settings on the server"
  hosts: all
  tags: config_and_settings

  tasks:
    - name: "Execute tasks to implement config and settings for the webserver"
      ansible.builtin.include_tasks:
        file: ./tasks/config_and_settings_on_the_web_server.yml


- name: "Setting up users"
  hosts: web_servers
  tags: web_servers_users

  tasks:
    - name: "Set the users"
      ansible.builtin.include_tasks:
        file: ./tasks/create_users.yml


- name: "Copying the server app to remote web_servers locations"
  hosts: web_servers
  tags: copy_webserver_app

  tasks:
    - name: "Transfer the app"
      ansible.builtin.include_tasks:
        file: ./tasks/transfer_the_fast_webserver.yml

- name: "Prepare and start the fastwebserver as a systemd service"
  hosts: web_servers
  tags: transfer_and_start_webserver_app

  tasks:
    - name: "Execute the transfer of the systemd template and starting of the app"
      ansible.builtin.include_tasks:
        file: ./tasks/prepare_to_run_fast_webserver.yml


- name: "Test if the webservers are operationals"
  hosts: web_servers
  tags: testing_webservers
  
  tasks:
    - name: "Test connection"
      ansible.builtin.include_tasks:
        file: ./tasks/checking_the_webserver.yml
...