---
for_linux_os: 
  - nmap-ncat 
  - curl 
  - tcpdump 
  - wget 
  - traceroute 
  - tcptraceroute 
  - iperf 
  - netperf 
  - telnet
java_17_packages:
  - java-17-openjdk.x86_64
  - java-17-openjdk-devel.x86_64
  - java-17-openjdk-javadoc.x86_64
  - java-17-openjdk-static-libs.x86_64
...
